export { PATH as ACCOUNT_SETTINGS_PATH } from './accountSettings'
export { PATH as DASHBOARD_PATH } from './dashboard'
export { PATH as HOME_PATH } from './home'
export { PATH as LOG_IN_PATH } from './logIn'
export { PATH as PAGE_NOT_FOUND_PATH } from './pageNotFound'
export { PATH as SIGN_UP_PATH } from './signUp'
export { default as Router } from './Router'
